import { MD3DarkTheme, MD3LightTheme } from "react-native-paper";

export const THEMES = {
  spotify: {
    ...MD3DarkTheme,
    name: "Spotify",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#1DB954",
      secondary: "#1ed760",
      background: "#121212",
      surface: "#282828",
      surfaceVariant: "#333333",
    },
  },
  midnight: {
    ...MD3DarkTheme,
    name: "Midnight Blue",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#3d5afe",
      secondary: "#536dfe",
      background: "#0a0b10",
      surface: "#161b22",
      surfaceVariant: "#21262d",
    },
  },
  purple: {
    ...MD3DarkTheme,
    name: "Deep Purple",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#bb86fc",
      secondary: "#03dac6",
      background: "#121212",
      surface: "#1e1e1e",
      surfaceVariant: "#2c2c2c",
    },
  },
  sunset: {
    ...MD3DarkTheme,
    name: "Sunset Orange",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ff5722",
      secondary: "#ff9800",
      background: "#1a1a1a",
      surface: "#2d2d2d",
      surfaceVariant: "#3d3d3d",
    },
  },
  crimson: {
    ...MD3DarkTheme,
    name: "Crimson Red",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#dc143c",
      secondary: "#ff4d4d",
      background: "#120a0a",
      surface: "#251616",
      surfaceVariant: "#3a2222",
    },
  },
  forest: {
    ...MD3DarkTheme,
    name: "Forest Green",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#2e7d32",
      secondary: "#4caf50",
      background: "#0d130d",
      surface: "#1b241b",
      surfaceVariant: "#2a362a",
    },
  },
  golden: {
    ...MD3DarkTheme,
    name: "Golden Glow",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ffd700",
      secondary: "#ffec8b",
      background: "#1a1600",
      surface: "#2b2500",
      surfaceVariant: "#3d3400",
    },
  },
  ocean: {
    ...MD3DarkTheme,
    name: "Ocean Breeze",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#0077be",
      secondary: "#00a9d8",
      background: "#001a2c",
      surface: "#002b49",
      surfaceVariant: "#003d66",
    },
  },
  lavender: {
    ...MD3LightTheme,
    name: "Lavender Mist",
    colors: {
      ...MD3LightTheme.colors,
      primary: "#967bb6",
      secondary: "#b39eb5",
      background: "#f3f0f7",
      surface: "#ffffff",
      surfaceVariant: "#e6e1ed",
    },
  },
  slate: {
    ...MD3DarkTheme,
    name: "Slate Gray",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#708090",
      secondary: "#778899",
      background: "#1c1c1c",
      surface: "#2f4f4f",
      surfaceVariant: "#4682b4",
    },
  },
  amoled: {
    ...MD3DarkTheme,
    name: "AMOLED Black",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ffffff",
      secondary: "#e0e0e0",
      background: "#000000",
      surface: "#121212",
      surfaceVariant: "#1e1e1e",
    },
  },
  rose: {
    ...MD3DarkTheme,
    name: "Rose Pink",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#e91e63",
      secondary: "#f06292",
      background: "#1a0a10",
      surface: "#2d121b",
      surfaceVariant: "#401a27",
    },
  },
  teal: {
    ...MD3DarkTheme,
    name: "Teal Dream",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#008080",
      secondary: "#20b2aa",
      background: "#001212",
      surface: "#002424",
      surfaceVariant: "#003636",
    },
  },
  coral: {
    ...MD3DarkTheme,
    name: "Coral Reef",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ff7f50",
      secondary: "#ff6347",
      background: "#1a0f0a",
      surface: "#2d1a12",
      surfaceVariant: "#40261a",
    },
  },
  lime: {
    ...MD3DarkTheme,
    name: "Neon Lime",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#32cd32",
      secondary: "#7cfc00",
      background: "#0a1a0a",
      surface: "#122d12",
      surfaceVariant: "#1a401a",
    },
  },
  amber: {
    ...MD3DarkTheme,
    name: "Royal Amber",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ffbf00",
      secondary: "#ffaa00",
      background: "#1a1200",
      surface: "#2d1f00",
      surfaceVariant: "#402d00",
    },
  },
  indigo: {
    ...MD3DarkTheme,
    name: "Indigo Night",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#4b0082",
      secondary: "#8a2be2",
      background: "#0a001a",
      surface: "#12002d",
      surfaceVariant: "#1a0040",
    },
  },
  cherry: {
    ...MD3LightTheme,
    name: "Cherry Blossom",
    colors: {
      ...MD3LightTheme.colors,
      primary: "#ffb7c5",
      secondary: "#ff69b4",
      background: "#fff5f7",
      surface: "#ffffff",
      surfaceVariant: "#ffe0e6",
    },
  },
  cyan: {
    ...MD3DarkTheme,
    name: "Electric Cyan",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#00ffff",
      secondary: "#00ced1",
      background: "#001a1a",
      surface: "#002d2d",
      surfaceVariant: "#004040",
    },
  },
  coffee: {
    ...MD3DarkTheme,
    name: "Coffee Roast",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#6f4e37",
      secondary: "#a67b5b",
      background: "#1a120d",
      surface: "#2d1f16",
      surfaceVariant: "#402d20",
    },
  },
  mint: {
    ...MD3LightTheme,
    name: "Mint Fresh",
    colors: {
      ...MD3LightTheme.colors,
      primary: "#98ff98",
      secondary: "#00ff7f",
      background: "#f0fff4",
      surface: "#ffffff",
      surfaceVariant: "#e0f7e6",
    },
  },
  hotpink: {
    ...MD3DarkTheme,
    name: "Hot Pink",
    colors: {
      ...MD3DarkTheme.colors,
      primary: "#ff69b4",
      secondary: "#ff1493",
      background: "#1a000d",
      surface: "#2d0016",
      surfaceVariant: "#400020",
    },
  },
};

export type ThemeKey = keyof typeof THEMES;
